### ISSUE TITLE
Notebook order

### ISSUE THREAD

**Issue by TomAugspurger** [TomAugspurger/dask-tutorial-pycon-2018#2]
1. Delayed
2. dataframe
3. schedulers
4. arrays?
5. distributed intro
6. distributed dataframes
7. distributed advanced (concurrent.futures)
8. ML?

cc @jcrist @martindurant

**Comment by jcrist** [comment]
My suggested order:

1. Delayed
2. Arrays
3. Dataframe
4. Schedulers
5. Distributed dataframes
6. Distributed advanced (futures)
7. Ecosystem, further resources, "homework"

Reasoning:
- Delayed is easy to understand, and gets people used to thinking in terms of graphs and delayed operations.
- I'd say numpy is more commonly understood than pandas, and the graphs are prettier. Good way to move from building graphs directly to "dask builds graphs for you".
- Dataframes have more interesting examples, and can ease people into the larger distributed examples later.
- Talk about schedulers to say how things run
- Just dive into using the distributed scheduler on larger dataframe problems, introducing concepts (dashboard, client) as needed
- The distributed scheduler also has additional features, discuss some of them
- The dask ecosystem is larger than just `dask`, here's some other projects you might be interested in. An updated version of https://github.com/jcrist/dask-tutorial-pydata-seattle-2017/blob/master/05-dask-ecosystem.ipynb might be nice.

**Comment by TomAugspurger** [comment]
That order sounds great to me I worry a bit that "Schedulers" comes too late, but for a tutorial it'll be fine.
