### ISSUE TITLE
Data Files

### ISSUE THREAD

**Issue by TomAugspurger** [TomAugspurger/dask-tutorial-pycon-2018#3]
What do we want to include? @jcrist's tutorial from PyData Seattle used nycflights, which is 42M compressed. Do we want to include that in the repo, or throw it on S3 / GCSFS and download it in a prep script?

**Comment by TomAugspurger** [comment]
I'll think about it for docker images.

I think we'll want some way for the users to have it locally if they're just using miniconda.

**Comment by martindurant** [comment]
gcs or s3 with public access it totally fine for this kind of thing. I wouldn't put it in the repo.

**Comment by TomAugspurger** [comment]
I uploaded nycflights to GCS, and updated `prep_data.py` to download it. Anyone able to pull master and try that out?

LMK if there are other files you want on GCS and I can upload them.

**Comment by martindurant** [comment]
```
18     os.makedir(data_dir)  => os.mkdir(data_dir
```
Otherwise fine.

**Comment by TomAugspurger** [comment]
Fixed, thanks. I think the error in `df.tail` is intentional in that notebook.

**Comment by martindurant** [comment]
Oh yes, just read a couple of lines further on...

**Comment by TomAugspurger** [comment]
@jcrist I copied the array notebook from `dask/dask-tutorial` along with the data prep for weather and the random HDF5 file. Feel free to use those or something else entirely.
